name: Build Docker Images
on:
  push:
    branches:
      - main
    tags:
      - '*'
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Docker Image
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/pewe79/cloudmucast.com
          tags: |
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=branch
            type=semver,pattern={{version}}
      - name: Publish Docker Image (Builtin Build)
        uses: docker/build-push-action@v4
        with:
          context: .
          target: builtin
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/pewe79/cloudmucast.com:builtin